import { ArrowLeft, ArrowRight, BadgeIndianRupee, CheckCircle2, ShieldAlert } from "lucide-react";
import { useState } from "react";
import type { DemoPaymentMode, FilingReview, PaymentProof } from "@/types/filing";

export function PaymentStep({ review, paymentProof, pending, onBack, onCreatePayment, onSubmit }: { review: FilingReview; paymentProof: PaymentProof | null; pending: boolean; onBack: () => void; onCreatePayment: (mode: DemoPaymentMode) => void; onSubmit: () => void }) {
  const exempt = review.feeStatus === "bpl_exempt";
  const [mode, setMode] = useState<DemoPaymentMode>(exempt ? "bpl_exempt" : "demo_upi");
  const amount = paymentProof ? new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(paymentProof.payment.amountPaise / 100) : null;
  return (
    <section className="step-panel" aria-labelledby="filing-step-title">
      <div className="step-heading"><p className="section-index">Submit</p><h1 id="filing-step-title" tabIndex={-1}>{exempt ? "Confirm the BPL fee exemption." : "Complete the demo payment step."}</h1><p>The amount and exemption status below come from your reviewed application.</p></div>
      <div className="demo-payment-banner"><ShieldAlert aria-hidden="true" /><div><strong>DEMO PAYMENT</strong><p>This is a prototype payment step. No real government payment is being processed.</p></div></div>
      {!paymentProof ? <div className="payment-panel"><div className="payment-amount"><BadgeIndianRupee aria-hidden="true" /><span>{exempt ? "Fee exempt" : "₹10.00"}</span><small>{exempt ? "BPL status, subject to proof metadata" : "Prototype standard RTI filing fee"}</small></div>{exempt ? <p className="exemption-copy">RTI Saathi will create a fee-exemption proof for this demo application. No payment details are collected.</p> : <fieldset className="payment-methods"><legend>Choose a demo method</legend><label><input type="radio" name="payment-method" checked={mode === "demo_upi"} onChange={() => setMode("demo_upi")} /><span>Demo UPI</span></label><label><input type="radio" name="payment-method" checked={mode === "demo_card"} onChange={() => setMode("demo_card")} /><span>Demo card</span></label><label><input type="radio" name="payment-method" checked={mode === "demo_netbanking"} onChange={() => setMode("demo_netbanking")} /><span>Demo net banking</span></label></fieldset>}<p className="payment-safety">RTI Saathi will not ask for a card number, CVV, UPI PIN, bank password or real payment credentials.</p><button className="button button--primary button--large" type="button" disabled={pending} onClick={() => onCreatePayment(mode)}>{pending ? "Creating secure demo proof…" : exempt ? "Confirm fee exemption" : "Complete demo payment"}</button></div> : <div className="payment-issued"><CheckCircle2 aria-hidden="true" /><div><p>{paymentProof.payment.status === "not_required" ? "Fee exemption confirmed" : "Demo payment confirmed"}</p><strong>{amount}</strong><small>{paymentProof.payment.transactionId ? `Demo reference: ${paymentProof.payment.transactionId}` : "No payment required"}</small><span>Proof valid until {new Date(paymentProof.expiresAt).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}</span></div></div>}
      {paymentProof ? <div className="final-submit-box"><h2>Ready to create your RTI Saathi application</h2><p className="mandatory-notice">This creates a prototype RTI Saathi application. It does not send your RTI directly to a government portal.</p><button className="button button--primary button--large" type="button" onClick={onSubmit} disabled={pending}>{pending ? "Creating your application…" : <>Submit to RTI Saathi <ArrowRight aria-hidden="true" /></>}</button></div> : null}
      <div className="step-actions step-actions--single"><button className="button button--secondary button--large" type="button" onClick={onBack} disabled={pending}><ArrowLeft aria-hidden="true" /> Back to review</button></div>
    </section>
  );
}
